### ISSUE TITLE
Argo tunnel

### ISSUE THREAD

**Issue by moisesrodriguez** [karanpratapsingh/preview-environments#11]
I'm going to customize a little bit this solution to my needs. I've completed a full preview deployment of my backend service, but in order for QA and product to test the app, I need a frontend deployed which I want to deploy in S3. The only thing I don't completely grasp yet is how you point the Argo tunnel to the Fargate app? Because I want to change it to point to the s3 bucket, which in turn that frontend will point to the Fargate app within the VPC. If you can give me some pointer, it would be much appreciated.

**Comment by karanpratapsingh** [comment]
Sure, feel free to fork and customize to your need, to keep this repository general I will not accept particular customization as of now. As for fargate, It's the other way around, fargate app reaches out to cloudflare via argo tunnel.

**Comment by moisesrodriguez** [comment]
Yes, any custom changes will be kept on my fork. I do see now that in the Dockerfile clouflared is installed and in the entrypoint this is run
```
cloudflared service install
service cloudflared start
```
Do you have any pointers as how to get the cloudflared service to proxy to a S3 bucket? I'm not familiar with argo tunnels, first time using them.
