### ISSUE TITLE
Cloudflare account details

### ISSUE THREAD

**Issue by moisesrodriguez** [karanpratapsingh/preview-environments#3]
Hello,

Looking at the `config.ts` it asks for the following:

```
 api_key: env.get('CLOUDFLARE_API_KEY').required().asString(),
 token: env.get('CLOUDFLARE_API_TOKEN').required().asString(),
 accountId: env.get('CLOUDFLARE_ACCOUNT_ID').required().asString(),
 zoneId: env.get('CLOUDFLARE_ZONE_ID').required().asString(),
 domain: '<todo-your-cloudflare-domain>',
```    

I've found how to create a API Key and a API Token, but have not found the Account ID and Zone ID. Where do you get them from?

For example for the token are these permissions enough?
![Screen Shot 2022-02-07 at 13 23 22](https://user-images.githubusercontent.com/3869040/152857599-11c3c689-c581-43f8-856c-d52773250af7.png)

For the cloudfare domain, where you get that from?

**Comment by karanpratapsingh** [comment]
Once you've created the a site in cloudflare dashboard, it's available in overview

<img width="1178" alt="Screenshot 2022-02-08 at 1 05 45 AM" src="https://user-images.githubusercontent.com/29705703/152859261-671a62a1-7209-445c-ba92-e45e9d9fe382.png">

**Comment by moisesrodriguez** [comment]
Ok, it is asking me to change my nameserver to Cloudflare, in this case is this necessary? Can I just leave it without changing my nameservers and use the Zone ID and Account ID? 

I'm managing my domain with AWS Route53 and don't want to change it to Cloudflare, but if for this to work, if it is necessary I can probably buy another domain for this preview environments. But want to check if this is necessary first.

**Comment by karanpratapsingh** [comment]
In my case, I had 2 separate domains. The main domain was hosted on Route53 and the preview environment had a random domain setup on Cloudflare.
